---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

I consider myself fortunate and privilledged to work with so many brilliant minds over the last view years.<br>
This page lists some of my work with NASA.<br>

## NASA Globe Program

<p align="justify">I have been accepted to the [NASA Globe Program](https://www.globe.gov/) as SETM scientist in the area of artificial intelligence and machine-learning.<br>

NASA Globe is a global science and education program supported by the [National Science Foundation](https://www.nsf.gov/), [National Oceanic and Athmospheric Administration](http://www.noaa.gov/) and the [United States Department of State](https://www.state.gov/).</p>

My pofile can be found [here](https://www.globe.gov/web/frank.soboczenski/home).

## NASA FDL

<!--I am amongst the finalists to attend the 2018 NASA Frontier Development Lab (FDL) at the [SETI Institute](https://www.seti.org/) in Mountain View, California.<br>
My project pool that I'll be working on is:

### Category I: Space Weather

<p align="justify"><b>Find new influences of solar dynamics on terrestrial systems</b><br>
During the FDL 2017 program cycle, the “Solar-Terrestrial Interactions” team showed that neural nets could be trained to use solar wind data to predict the Kp Index (a measure of geomagnetic storm severity). This challenge proposes to take this initial step even further, and will use solar wind data from L1 satellite observatories, such as SOHO, to find new causality indications for solar-terrestrial interactions, such as global weather patterns, lightning strikes and - potentially even earthquakes.</p>

<p align="justify"><b>Show tomorrow's sun today</b><br>
The goal of this challenge would use many terabytes of historic SDO AIA images to build a neural net model to produce a forecast of what the sun will look like 24 hours into the future. The trained neural net model would ingest a time-series sequence of AIA images leading up to the present moment, and output an image of the sun as it is predicted to appear in 24 hours.</p>

<p align="justify"><b>Predicting solar spectral irradiance from SDO/AIA observations</b><br>
Solar spectral irradiance is a critical factor for determining the properties of the Earth's upper atmosphere. Its short-term variability due to solar flares and CMEs could significantly disturb the upper atmosphere of the Earth and increase atmospheric drag on orbiting satellites. The goal of this challenge is to develop an AI model which uses SDO/AIA images to predict solar spectral irradiance (SSI) at Extreme Ultraviolet (EUV), and soft X-ray wavelengths. The EUV/X-ray SSI is an important energy input for terrestrial upper atmospheric models, which has important implications for everything from satellite orbital drag to the long-term evolution of the Earth’s atmosphere.</p>

### Category II: Exoplanets

<p align="justify"><b>Increase the efficacy and yield of exoplanets detection from TESS</b><br>
TESS’s mission to discern credible exoplanet signatures is an imposing data task. Moreover any follow-up strategy to further examine interesting candidates is made more demanding because of a mission time constraint, where follow-ups need to be identified each and every month as the spacecraft changes its field of view. At the moment, diagnosis of Exoplanet candidates still requires manual analysis - an impossibly big challenge for humans in the time window available. This time crunch problem remains unresolved, but may be suited to AI approaches. Can we develop AI techniques to resolve the time window problem, by automating the classification analysis currently done by human experts?</p>

<p align="justify"><b>Codify the process of AI derived exoplanet discovery and Cclassification to help TESS better discern rocky planets.</b><br>
Can we use data from Kepler, K2 and and human analysis to develop a method to improve TESS’s ‘Lilith’ simulator factoring a range of stellar properties and occurrence rates and well as develop an ‘explainable AI’ that can learn to better discern rocky classifications as time goes on and identify the key features factored in the analysis? In addition to possible improvements to Lilith this challenge would look to identify improvements to the detection pipeline, not just in the transit detection but also upstream data reduction. I.e. what pixel calibration errors are most detrimental? how best to remove systematics? which systematics cause the most issues? and also identifying improved vetoes in the transiting planet search module.</p>
-->
## NASA Space Apps 

<p align="justify">For more than 5 years, I am active as lead-organiser or organising comittee member of the NASA Space Apps Challenge in York. I look back on many amazing memories and fantastic software development moments. More information can be found at [Space Apps Challenge](https://2017.spaceappschallenge.org/) or the previous York specific events:</p>

- [NASA Space Apps York 2017](https://2017.spaceappschallenge.org/locations/york/)<br>
- [NASA Space Apps York 2016](https://2016.spaceappschallenge.org/locations/york-england)<br>
- [NASA Space Apps York 2015]()<br>
- [NASA Space Apps York 2014]()<br>
- [NASA Space Apps York 2013]()<br>

Our team [LaunchSight]() won the 2016 Challenge and was invited amonst other global winning teams to [NASA Kennedy Space Center](https://www.kennedyspacecenter.com/). We had the opportunity to meet so many amazing people and attend the [OSIRIS REx](https://www.asteroidmission.org/) mission launch. X the Z, Beth the C and R the x were among the many amazing people I've met at my time at NASA. 

Pictures can be found here:.
 
## NASA ENSPIRES 

<p align="justify">I currently serve as program reviewer for the Translational Research Institute for Space Health (TRISH) project under the Biomedical Research Advances for Space Health (BRASH) branch.</p>  
