---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Current Roles

### General

- [ML4PS: Machine Learning and the Physical Sciences - Workshop at the 33rd Conference on Neural Information Processing Systems (NeurIPS), 2019](https://ml4physicalsciences.github.io) Program Committee/Reviewer<br>
- [ML4HL: Machine Learning for Health Workshop at NeurIPS 2019](https://ml4health.github.io) Program Committee/Reviewer<br>
- [The 57th Annual Meeting of the Association for Computational Linguistics (ACL)](http://www.acl2019.org/EN/index.xhtml) Program Committee (Machine Learning)<br>
- [American Medical Informatics Association (AMIA) Annual Symposiumn 2019](https://www.amia.org/amia2019) Reviewer<br>
- [DataKind & Google.AI](http://www.datakind.org) Impact Challenge Reviewer<br>
- [IEEE Journal of Biomedical and Health Informatics](https://jbhi.embs.org/) Reviewer<br>

### King's College London

- [R User Group](https://www.kcl.ac.uk) Main Organiser<br>
- [Masters of Public Health](https://www.kcl.ac.uk/study/postgraduate/taught-courses/public-health-mph.aspx) Tutor, Dissertation Marking<br>
- [Low Risk Ethics Commitee](https://www.kcl.ac.uk/innovation/research/support/ethics/committees/bdm/index.aspx) Reviewer<br>

## Past Roles

### General

- [Journal Interacting with Computers (IwC)](https://academic.oup.com/iwc) Reviewer<br>

### University of York

- [Master of Science in Cyber Security](https://www.york.ac.uk/study/postgraduate-taught/courses/msc-cyber-security/) Associate Lecturer<br>
- [R Users Day York - RUDY](https://sites.google.com/a/york.ac.uk/r-users-york/news/rseminarseriesr-markdown?pli=1) Co-Organiser<br>
- [Computer Science - Research Student Seminars](https://cs.york.ac.uk) Co-Organiser<br>
- [Computer Science](https://www.cs.york.ac.uk/) Teaching Assistant<br>

### Deggendorf Institute of Technology

- [AI / Prolog programming](https://www.th-deg.de/en) Instructor<br>
- [Computer Science & Business Economics](https://www.th-deg.de/en) Lab Instructor<br>
- [Mensa](https://www.th-deg.de/en) Student Representative<br>
