---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

<p align="justify">I've developed numerous applications for science and industry on multiple platforms. Some are listed below:</p>

## Deep Learning
<p align="justify">There are several projects currently in development. Those range from NLP to Image data analysis.<br>
Also keep an eye on my [Github](https://github.com/h21k) repositories.</p>

## IBM
<p align="justify">I am part of a <b>hyperledger</b> project that utilises IBM's Cloud (former Bluemix) & Softlayer platform.</p>

## Facebook Artificial Intelligence Group
<p align="justify">While mostly working with Tensorflow and Keras, I am currently exploring and devloping a <b>PyTorch</b> course on classifying Randomised Controlled Trials (RCTs).</p>

## Google Apps Engine 

- [`Test Proxy Server`](https://uslesstest.appspot.com/)
- [`Task Manager with Collaboration Functionality`](https://angryslugs.appspot.com/)
- [`Geographic Chat`](https://angrycoffeemonster.appspot.com/)
- [`Google Home on Raspberry Pi`](https://www.google.com)

## iOS (iPhone/iPad)
- `B.Braun Number-Entry Interface`
- `Serial Number-Entry interface`
- `iPad Game - Memorize or Die`
- `iPad Game - Bug in a Tube`
- `iPhone App - NASA SpaceApps Challenge 2014 York`
- `Tensorflow lite - various phone applications`
- `IBM cloud - various machine learning phone applications`

## Others

- R, Shiny, C++, Python, Java, Flask, Ada, Raspbian, and many more...

<p align="justify">You can find most of my public codes on [Github](https://www.github.com/h21k) or [Gitlab](https://gitlab.com/h21k). Feel free to [contact me](contact.html) about specific requests on tools or if you want me to join your development team.</p>
