---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Upcoming

2018 [AI Tech World / London Tensorflow](http://aitechworld.net/): <b>*NASA FDL Project*</b> (more info soon)<br>
2018 Google Campus: <b>*RobotReviewer*</b><br>
2018 King's College: <b>*RobotReviewer Day*</b><br>
2018 King's College R User Group: <b>*Using Jupyter Notebooks with R*</b><br>

<!-- 
2018 IBM: <b>*RobotReviewer: Automatic Evidence Synthesis for Randomised Controlled Trials*</b><br>
-->

## Invited Speaker

2015 <b>*RStudio and version control with Git/Github.*</b> The 3rd R-Users day in York.<br>
2015 <b>*A road map to reduce number-entry errors.*</b> The University of York Department of Psychology. Invited by Dr. Silke Goebel<br>
2015 <b>*Three minutes research presentation.*</b> The University of Sheffield<br>
2015 <b>*Research presentation*</b> The Department of Computer Science: Research students seminars series<br>
2014 <b>*Data Visualisation with RStudio.*</b> The 2nd R-Users day in York.<br>
2013 <b>*Introduction to RStudio.*</b> The 1st R-Users day in York.<br>
2013 <b>*Reducing number-entry errors in medical devices.*</b> The Department of Computer-Science Human-Computer Interaction Group<br>
2012 <b>*5-Key medical device safety.*</b> CHI+MED Number-Entry Workshop at Swansea University<br>

## Conference Talks

Bayesian Deep Learning for Exoplanet Atmospheric Retrieval. Bayesian Deep Learning Workshop at the 32nd Conference on Neural Information Processing Systems (NeurIPS), Montreal

<p align="justify">2018 <b>*Bayesian Deep Learning for Exoplanet Atmospheric Retrieval.*</b> Bayesian Deep Learning Workshop at the 32nd Conference on Neural Information Processing Systems (NeurIPS), Montreal <b>*Presented by [Michael Himes](https://sciences.ucf.edu/physics/people/himes-michael/)*</b></p>

<p align="justify">2018 <b>*Deep learning for exoplanet atmospheric retrievals.*</b> NASA Technosignatures workshop Houston, Texas<br></p>

<p align="justify">2015 <b>*Study of the Reliability of Statistical Timing Analysis for Real-Time Systems.*</b> 23rd International Conference on Real Time and Networks Systems - RTNS'15<br></p>

<p align="justify">2014 <b>*The Effects of Perceptual Interference on Number-Entry Errors.*</b> First Int. conf. on Interaction Design and Human Factors, Kochi Japan</br></p>

<p align="justify">2013 <b>*Increasing Accuracy by Decreasing Presentation Quality in Transcription Tasks.*</b> Interact Capetown</br></p>

